#!/usr/bin/env bash

percent_value="$1"

if [ x"$percent_value" = x ]; then
    percent_value=1
fi

echo "setting screen brightness to $percent_value of maximum"

max_brightness=`cat /sys/class/backlight/intel_backlight/max_brightness`

brightness=`echo "$percent_value * $max_brightness"| bc`
brightness=`printf "%.0f" $brightness`

echo "max_brightness = $max_brightness"
echo "brightness = $brightness"
echo "$brightness" | sudo tee /sys/class/backlight/intel_backlight/brightness
